pipeline {
    agent any
 
    stages {

        stage('Checkout code') {
            agent any
            steps {
                git branch: 'source', url:'https://github.com/sofiane1234/m2-cicd'
                sh 'ls -R ${WORKSPACE}'
            }
        }

        stage('Build Backend') {
            agent {
                label 'docker-agent-python'
            }
            steps {
                sh 'ls -R'
                sh 'pip install -r back/requirements.txt'
                echo 'Building..'
            }
        }
        stage('Test') {
            agent {
                label 'docker-agent-python'
            }
            steps {
                echo 'Unit Testing...'
                echo 'Installing pytest'
                sh 'pip install pytest pytest-junitxml'
                sh 'pytest back/tests --maxfail=5 --disable-warnings --tb=short --junitxml=test-results/results.xml'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }

    post {
        always {
            junit 'test-results/results.xml'
        }
    }
}